repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-case-conflict
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        # args: [.git/COMMIT_EDITMSG]
        # pass_filenames: false
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: check-unix-filenames
        name: check unix/linux filename validity
        entry: bash cli/check_unix_filenames.sh
        language: system
        types: [file]
      - id: export-dependencies
        name: export dependencies
        entry: bash cli/export_deps.sh
        language: system
        types: [file]
        pass_filenames: false
      - id: unit-tests
        name: checking unit tests
        entry: poetry run python -m unittest discover -s tests/unit -p "*.py"
        language: system
        types: [file]
        pass_filenames: false
      - id: integration-tests
        name: checking integration tests
        entry: poetry run python -m unittest discover -s tests/integration -p "*.py"
        language: system
        types: [file]
        pass_filenames: false