site_name: stpstone
repo_url: https://github.com/guilhermegor/stpstone
repo_name: guilhermegor/stpstone
edit_uri: tree/main/docs

theme:
  name: material
  language: en
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

