[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::RuntimeWarning:divide by zero encountered in scalar divide
    ignore::RuntimeWarning: divide by zero encountered in scalar divide
    ignore:divide by zero encountered in scalar divide:RuntimeWarning